# Generated by Django 4.1.3 on 2023-12-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_listinghouse_booked_users_alter_listinghouse_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinghouse',
            name='approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
