# Generated by Django 4.1.3 on 2023-12-17 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_listinghouse_crated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinghouse',
            name='booked_users',
            field=models.ManyToManyField(blank=True, related_name='booked_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listinghouse',
            name='crated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
