# Generated by Django 4.1.3 on 2023-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_listinghouse_booked_users_bookinghouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghouse',
            name='status',
            field=models.CharField(blank=True, choices=[('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_ON_PROCESS', 'Request On Process'), ('REQUEST_COMPLETED', 'Request Completed')], default='REQUEST_ON_PROCESS', max_length=100, null=True),
        ),
    ]
