# Generated by Django 4.1.3 on 2023-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bookinghouse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghouse',
            name='crated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
