# Generated by Django 4.1.3 on 2023-12-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_bookinghouse_crated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghouse',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('on_process', 'Request On Process'), ('completed', 'Request Completed')], default='REQUEST_ON_PROCESS', max_length=100, null=True),
        ),
    ]
