# Generated by Django 4.1.3 on 2023-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_bookinghouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghouse',
            name='status',
            field=models.CharField(blank=True, choices=[('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_ON_PROCESS', 'Request On Process'), ('REQUEST_COMPLETED', 'Request Completed')], default='REQUEST_ON_PROCESS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listinghouse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
