# Generated by Django 4.1.3 on 2023-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_bookinghouse_status_alter_listinghouse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='unapproved',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Profile_pic/'),
        ),
    ]
